name: Build CLI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.tag-name.outputs.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set tag name
        id: tag-name
        run: echo "name=cli" >> $GITHUB_OUTPUT
      - name: Create tag
        run: |
          TAG="${{ steps.tag-name.outputs.name }}"

          if git ls-remote --tags origin | grep -q "refs/tags/$TAG"; then
            echo "Tag already exists on remote"
          else
            git tag $TAG
          fi

          git push origin $TAG

      - name: Enable Corepack
        run: npm i -g --force corepack && corepack enable

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - uses: oven-sh/setup-bun@v1

      - name: Make binaries executable
        run: |
          chmod +x worcable-*

      - name: Build CLI
        run: |
          bun build src/index.ts --compile --target=bun-linux-x64 --outfile cli/worcable-linux-amd64
          bun build src/index.ts --compile --target=bun-linux-arm64 --outfile cli/worcable-linux-arm64
          bun build src/index.ts --compile --target=bun-darwin-x64 --outfile cli/worcable-darwin-amd64
          bun build src/index.ts --compile --target=bun-darwin-arm64 --outfile cli/worcable-darwin-arm64

      - name: Make binaries executable
        run: chmod +x cli/worcable-*

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cli/worcable-linux-amd64
            cli/worcable-linux-arm64
            cli/worcable-darwin-amd64
            cli/worcable-darwin-arm64
          tag_name: ${{ steps.tag-name.outputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
